# CHECKPOINT: Trying To fix TagBot
# - [Use PAT as token](https://github.com/JuliaRegistries/TagBot#personal-access-tokens-pats)
# - This script seems not yet correctly being set up. See [Setup](https://github.com/JuliaRegistries/TagBot#setup).
# - It seems TagBot should work on branch "release" pushed.
# - You should take how your SWCForecast packages organized into consideration for decide on when TagBot should work.


name: TagBot

on:
  push:
    paths:
      - 'Project.toml'
    branches:
      - master
      - main
  issue_comment:
    types:
      - created
  # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
  workflow_dispatch:
  # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
jobs:
  TagBot:
    # if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: okatsn/OkRegistry # for custom registry
          # If your registry is public, this is all you need to do.
          # For more information, see [here](https://github.com/JuliaRegistries/TagBot#custom-registries)


